version: '2'

networks:
  my-net:
    ipam:
      config:
        - subnet: 172.20.0.0/24
services:
  mysql8:
    build: ./files_docker/mysql8
    ports:
       - '3306:3306'
    environment:
           #- MYSQL_ROOT_USER=root
      - MYSQL_ROOT_PASSWORD=jtgEuZ8udR7F
      #Эти параметры передаются в /docker_files/mysql8/files/init.sh
      - MYSQL_ACCESS_IP=172.20.0.5
      - MYSQL_USER_LOGIN=gawric
      - MYSQL_USER_PASSWORD=jtgEuZ8udR7F
      - MYSQL_DATABASE=laravel
      - MYSQL_AUTHENTICATION_PLUGIN=mysql_native_password
         # - ALLOW_EMPTY_PASSWORD=yes
    volumes:
       - 'mysql_data:/bitnami/mysql/data'
    networks:
      my-net:
        ipv4_address: 172.20.0.4
  laravel:
    build: ./files_docker/laravel9
    stdin_open: true
    ports:
      - '8000:8000'
    networks:
      my-net:
        ipv4_address: 172.20.0.5
      #command: "composer install"
      #command:  "/bin/bash"
      #command: "php artisan migrate"
      #command: "php artisan key:generate"
    environment:
      - DB_HOST=mysql8
        # - DB_PORT=3306
        #- DB_USERNAME=bn_myapp
        # - DB_DATABASE=bitnami_myapp
        #volumes:
      #- './Lineage2-Kraken-Web:/app'
    depends_on:
      - mysql8
volumes:
  mysql_data:
    driver: local
